---

- tags: [ apache ]
  become: yes
  block:


    - name: install any repo provider packages before the main phase
      package:
        name: "{{ apache_packages_repo }}"
      tags: [ pkgs ]

    - name: install Apache Packages
      package:
        name:  "{{ apache_packages }}"
      tags: [ pkgs ]

    - name: Get version of Apache to select for changes between 2.2 and 2.4
      shell: |
        ( ( test -e /usr/bin/dpkg && dpkg -s {{ apache_package_name }} | grep '^Version:' | awk '{print $2}' ) || \
        ( test -e /bin/rpm && rpm -qa {{ apache_package_name }} --queryformat %{VERSION}) )
      register: apache_version_installed
      changed_when: False
      tags: always

    - debug:
        msg: "apache installed version is {{ apache_version_installed }}"
      tags: always
