---

- tags: [ apache, suite ]
  become: yes
  block:

  - include_tasks: ../bootstrap/scl-enable.yml
    vars:
      scl_pkgs: "{{ apache_scl_pkgs }}"

  - name: install any repo provider packages before the main phase
    package:
      name: "{{ apache_packages_repo }}"
    tags: [ pkgs ]

  - name: "install apache deps ({{ ansible_distribution }})"
    package:
      name: "{{ apache_packages }}"

  - name: create the Debian style available/enabled conf dirs
    file:
      path : "{{ apache_server_root }}/{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - sites-enabled
      - sites-available
      - mods-enabled
      - mods-available
      - conf-enabled
      - conf-available

  - name: httpd server conf with sites/mods/conf Imports
    template:
      src: conf/server-rh-httpd24-CentOS.conf
      dest: "{{ apache_main_conf_file }}"
      owner: root
      group: root
      mode: 0644
    notify:
      - restart apache

  # - name: set php security stuff
  #   template:
  #     src: templates/php_overrides.ini
  #     dest: "/etc/php.d/php_overrides.ini"
  #     owner: root
  #     group: root
  #     mode: 0644
  #   notify:
  #   - restart apache
  #   tags:
  #     - pkgs

  - name: repair the expected paths for tools that won't accept change
    file:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      state: link
    with_items:
      - { src: '/etc/rc.d/init.d/httpd24-httpd', dest: '/etc/init.d/httpd' }
      - { src: '/opt/rh/httpd24/root/etc/httpd', dest: '/etc/httpd' }
      # - { src: '/opt/rh/httpd24/root/usr/sbin/httpd', dest: '/usr/sbin/httpd' }
      # - { src: '/opt/rh/httpd24/root/usr/sbin/httpd', dest: '/usr/sbin/httpd' }

  - name: "fixup scl binaries for {{ item.pkg }}"
    copy:
      content: |
          #!/bin/bash
          source scl_source enable {{ item.pkg }}
          exec {{ item.src }} "$@"
      dest: '{{ item.dest }}'
      owner: root
      group: root
      mode: 0755
    with_items:
      - src: '/opt/rh/rh-php70/root/usr/bin/php'
        dest: '/usr/bin/php'
        pkg: rh-php70
      - src: '/opt/rh/httpd24/root/usr/sbin/httpd'
        dest: '/usr/sbin/httpd'
        pkg: httpd24

  # - name: create a list of logfiles for this host for global log shipper
  #   set_fact:
  #     logfiles: |
  #         {{ ( apache_system_logs | fixup_file_list(apache_log_path) )
  #             +  logfiles|default([]) }}
  #   notify: logfiles_changed
  #   tags: [ logfiles ]
  #   changed_when: false


