---

- tags: [ apache, suite ]
  become: yes
  block:

  - name: install apache deps
    package:
      name: "{{ apache_packages }}"

  - name: create the var cache directory
    file:
      name: "{{ apache_site_conf_path }}"
      state: directory

  - name: create the sites enabled directory
    file:
      name: /etc/httpd/sites-enabled
      state: directory

  - name: enable sites available/enabled dirs
    template:
      src: sites-available.conf
      dest: "{{ apache_conf_d_dir }}/xx_sites_enabled.conf"
      owner: root
      group: root
      mode: 0644
    notify:
    - restart apache

  - name: add the ssl more hardening file
    template:
      src: ssl-hardening/ssl-more-secure.conf
      dest: "{{ apache_conf_d_dir }}/ssl-more-secure.conf"
      owner: root
      group: root
      mode: 0644
    notify:
    - restart apache

  # - include_tasks: en2enmod-shim.yml
