---

- tags: [ apache ]
  become: yes
  block:

  - debug:
      var: apache_site_conf_path

  - debug:
      var: apache_profile

  - name: install httpd.conf file for {{ vhost.ServerName }}
    template:
      src: httpd-conf.j2
      dest: "{{ apache_site_conf_path }}/{{ vhost.ServerName }}.conf"
      owner: root
      group: root
      mode: 0644
    register: vhost_template_conf
    notify:
      - restart apache

  - name: link the en2ensite type scripts in
    file:
      src: "{{ apache_site_conf_path }}/{{ vhost.ServerName }}.conf"
      dest: "{{ apache_site_enabled_conf_path }}/{{ vhost.ServerName }}.conf"
      state: link

  # - name: enable the site {{ vhost.ServerName }}
  #   shell: |
  #     /usr/sbin/a2ensite {{ vhost.ServerName }}
  #   register: stdout
  #   notify:
  #     - restart apache

  - name: forcing restart of apache for this vhost
    service:
      name: "{{ apache_service }}"
      state: restarted
    when:
      - "'force_immediate_update' in vhost"
      - vhost_template_conf.changed
