---

- tags: [ apache, ssl ]
  become: True
  block:

  - name: find the distro specific installer
    include_tasks: "{{ include_apache_ssl_tasks }}"
    with_first_found:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_system }}.yml"
    loop_control:
      loop_var: include_apache_ssl_tasks
    tags: always